import random
import time
import csv
from datetime import datetime
from typing import Callable


TRIES = 10000
MINE = 9


def build_neighbors(side_length: int):
    """builds a list, where at index 0, returns all the neighbors of the tile at posititon 0. this list stays global and should be generated once

    Args:
        side_length (int): length of a side of the board

    Returns:
        list: a list with side_length**2 nested lists inside.
    """
    board_size = side_length * side_length
    neighbors = []

    for index in range(board_size):
        row = index // side_length
        col = index % side_length
        current = []

        for d_row in (-1, 0, 1):
            for d_col in (-1, 0, 1):
                if d_row == 0 and d_col == 0:
                    continue

                new_row = row + d_row
                new_col = col + d_col

                if 0 <= new_row < side_length and 0 <= new_col < side_length:
                    current.append(new_row * side_length + new_col)

        neighbors.append(current)

    return neighbors


def build_board(side_length: int, num_mines: int, neighbors: list):
    """builds the board, only called once at the begining of each game

    Args:
        side_length (int): length of each side of the board
        num_mines (int): number of mines on the board
        neighbors (list): generated neighbors list by build_neighbors(), see build_neighbors()

    Returns:
        list: generated board, should not be shown to or used by bot
    """
    board_size = side_length * side_length
    board = [0] * board_size

    mine_positions = random.sample(range(board_size), num_mines)

    for mine_index in mine_positions:
        board[mine_index] = MINE

    for mine_index in mine_positions:
        for neighbor in neighbors[mine_index]:
            if board[neighbor] != MINE:
                board[neighbor] += 1

    return board


def reveal_square(index: int, board: list, hidden: list, state: dict, num_mines: int):
    """reveals a square of the board and updates hidden and state based off board

    Args:
        index (int): index of tile to be revealed
        board (list): the actual minesweeper board
        hidden (list): the hidden list
        state (dict): state of game
        num_mines (int): number of mines on the board

    Returns:
        False | True | None | int: returns None if the game is already over, returns False if clicked tile is a mine, returns True if all safe tiles are clicked, and returns the value of the tile if none of the above.
    """
    if state["game_over"]:
        return None

    if not hidden[index]:
        return None

    hidden[index] = False

    if board[index] == MINE:
        state["game_over"] = True
        state["won"] = False
        return False

    state["safe_left"] -= 1

    if state["safe_left"] == 0:
        state["game_over"] = True
        state["won"] = True
        return True

    return board[index]


def flood_fill(
    start_index: int,
    board: list,
    hidden: list,
    state: dict,
    neighbors: list,
    num_mines: int,
    clues: dict | None = None,
):
    """if a 0 is clicked, click all surrounding tiles, and continue if any of those are zeros

    Args:
        start_index (int): index of the first tile to be clicked
        board (list): the non hidden board, with all values
        hidden (list): the hidden board, with only true or false, see smartishBot() for more info
        state (dict): the state of the game, see smartishBot()
        neighbors (list): generated by build_neighbors(), see build_neighbors()
        num_mines int): number of mines on the board
        clues (dict, optional): a dictionary of already revealed clues. Defaults to None (due to some bots not storing clues).
    """
    if state["game_over"]:
        return

    stack = [start_index]

    while stack and not state["game_over"]:
        current = stack.pop()

        for neighbor in neighbors[current]:
            if not hidden[neighbor]:
                continue

            result = reveal_square(neighbor, board, hidden, state, num_mines)

            if result is False or result is True:
                return
            elif result == 0:
                stack.append(neighbor)
            else:
                if clues is not None:
                    clues[neighbor] = result


def random_bot(
    side_length: int, num_mines: int, neighbors: list
):  # * this is a baseline bot that just gueses random indices every round
    start = time.perf_counter()
    board_size = side_length * side_length
    board = build_board(side_length, num_mines, neighbors)
    hidden = [True] * board_size
    state = {
        "game_over": False,
        "won": False,
        "safe_left": board_size - num_mines,
    }

    click_order = list(range(board_size))
    random.shuffle(click_order)

    for index in click_order:
        if state["game_over"]:
            break
        if not hidden[index]:
            continue

        result = reveal_square(index, board, hidden, state, num_mines)

        if result == 0:
            flood_fill(index, board, hidden, state, neighbors, num_mines)
    end = time.perf_counter()
    timeDelta = end - start
    return state["won"], timeDelta


# hello there!


def apply_reveal(
    index: int,
    board: list,
    hidden: list,
    state: dict,
    numMines: int,
    clues: dict,
    neighbors: list,
):
    result = reveal_square(index, board, hidden, state, numMines)
    if result is False:
        return "break"
    elif result is True:
        return "break"
    elif result == 0:
        flood_fill(index, board, hidden, state, neighbors, numMines, clues)
        if state["game_over"]:
            return "break"
    elif result is not None:
        clues[index] = result
    return result


def revealSafeTiles(
    tiles: list | set,
    hidden: list,
    board: list,
    state: dict,
    numMines: int,
    clues: dict,
    neighbors: list,
):
    for indexT in tiles:
        if hidden[indexT]:
            returnValue = apply_reveal(
                indexT, board, hidden, state, numMines, clues, neighbors
            )
            if returnValue == "break":
                return "break"


def deduce(
    clues: dict,
    hidden: list,
    flagged: set,
    updates: list,
    safe: set,
    neighbors: list,
):
    """helper function to smartishBot(), updates flagging for flagged mines and flagged safe squares"""

    for indexV, value in clues.items():
        flaggedNeighbor = 0
        totalHidden = []
        for neighbor in neighbors[indexV]:
            if hidden[neighbor]:
                if neighbor not in totalHidden:
                    if neighbor not in flagged:
                        totalHidden.append(neighbor)
                    else:
                        flaggedNeighbor += 1
        if len(totalHidden) == value - flaggedNeighbor:
            for el in totalHidden:
                if el not in flagged:
                    flagged.add(el)
                    updates.append(el)
        if value - flaggedNeighbor == 0:
            for neighbor in totalHidden:
                if neighbor not in safe:
                    safe.add(neighbor)
                    updates.append(neighbor)


def make_heuristic(
    updates: list,
    board_size: int,
    hidden: list,
    flagged: set,
    clues: dict,
    neighbors: list,
    scoreValue: dict,
):
    """if/when needed generates a guess as to the next safest square, scans through all tiles and calculates score for each. sorts them into a list by accending score, so lowest first, then randomly picks one if scores are equal

    Args:
        updates (list): to keep track of updates, see smartishBot()
        board_size (int): side_length^2, total tiles
        hidden (list): hidden True or False list
        flagged (set): set of all indices that are flagged to get rid of duplicates
        clues (dict): already revealed clues
        neighbors (list): see build_neighbors()
        scoreValue (dict): score value is a dict that keeps track of the computed score in make_heuristic(), key is index, value is computed score

    Returns:
        string | int: returns either "continue" as a sign to continue in smartishBot(), or the index to guess next
    """
    # * no new information was found from deduction,
    # * so the bot has to guess using the heuristic.
    for i in range(board_size):

        total = 0

        # * only score tiles that are still hidden
        if hidden[i]:

            # * do not score tiles already flagged as mines
            if i not in flagged:

                # * look at all clue tiles neighboring this candidate tile i
                for neighbor in neighbors[i]:
                    if neighbor in clues:

                        # * flaggedNeighborSum = how many flagged mines
                        # * are already around this clue tile
                        flaggedNeighborSum = 0

                        # * totalNeighbor = how many hidden, unflagged tiles
                        # * are still unresolved around this clue tile
                        totalNeighbor = 0

                        # * scan the clue tile's neighbors
                        for neighborsNeighbor in neighbors[neighbor]:
                            if hidden[neighborsNeighbor]:
                                if neighborsNeighbor not in flagged:
                                    totalNeighbor += 1
                                else:
                                    flaggedNeighborSum += 1

                            # * if there are still unresolved tiles around this clue,
                            # * add this clue's risk contribution to tile i.
                            #
                            # (clue value - already flagged mines)
                            # ------------------------------------
                            # unresolved hidden neighbors
                            #
                            # * Lower total score means safer guess.
                        if totalNeighbor != 0:
                            total += (
                                clues[neighbor] - flaggedNeighborSum
                            ) / totalNeighbor

                    # * store the final heuristic score for tile i
                scoreValue[i] = total
            else:
                # * revealed tiles should never be chosen, so give them
                # * a large dummy score
                scoreValue[i] = 9

        # * sort all candidate tiles by score, lowest first
    sorted_dict = dict(sorted(scoreValue.items(), key=lambda item: item[1]))
    best = []
    minValue = 0
    x = 0
    # * collect all tiles tied for the lowest score
    for key, valueT in sorted_dict.items():
        if x == 0:
            # * first tile has the minimum score because dict is sorted
            best.append(key)
            minValue = valueT
        else:
            # * add all other tiles with the same minimum score
            if valueT == minValue:
                best.append(key)
            else:
                # * stop once scores get worse than the minimum
                break
        x += 1
        # * randomly choose one of the safest-scoring tiles
    index = best[random.randrange(len(best))]
    return index


def smartishBot(sideLength: int, numMines: int, neighbors: list):
    """this is a mine sweeper bot that uses heuristics and flagging in order to try to solve mine sweeper

    Args:
        sideLength (int): the side length of the board
        numMines (int): the number of mines on the board
        neighbors (list): list that is generated by build_neighbors(), see func build_neighbors() for more info

    Returns:
        tuple: tuple of (bool, float) bool: didWin, did the robot win the game. float: timeTaken, how much time elapsed
    """

    start = time.perf_counter()  # * start timer to track how long bot takes

    board_size = sideLength**2  # * calc board size bc its js a square

    board = build_board(sideLength, numMines, neighbors)  # * builds the board

    hidden = [
        True
    ] * board_size  # * hidden is the board that the bot sees, if hidden[index] is true, that tile is still hidden

    # * state is a variable used to track if the game is over, what the result is after the game runs, and the amount of safe tiles left.
    state = {
        "game_over": False,  # * is the game over? used for the main while loop
        "won": False,  # * did the bot win? is the returned value by smartish bot
        "safe_left": board_size
        - numMines,  # * how many safe tiles are left, used to update game over and won
    }

    clues = {}
    # * clues is a list used to keep track of revealed tiles and there scores, key:index value:score.
    # * updated in reveal functions

    flagged = set()  # * flagged and safe are sets in order to prevent duplicate entries
    safe = set()  # * also more efficient to check is x in x for sets compared to list

    index = random.randrange(0, board_size)  # * first guess is always random

    while not state["game_over"]:  # * while the game is still running

        returnValue = apply_reveal(
            index, board, hidden, state, numMines, clues, neighbors
        )

        # * apply reveal returns either
        # *  "break" if the game is over
        # *  or the result of the guess, which then gets appended to the dict clues with key being index and value being what number it is

        if returnValue == "break":
            break

        scoreValue = {}

        # * score value is a dict that keeps track of the computed score in make_heuristic()
        # * key is index, value is computed score
        # * is used to make heuristic when needed in make_heuristic()

        while True:
            updates = []
            # * Updates is a list used to keep track of any updates made during this loop, if updates isnt empty, it repeats the loop
            # * updates is popualated if a tile is marked safe or if a tile is flagged
            deduce(clues, hidden, flagged, updates, safe, neighbors)

            if len(safe) > 0:
                if (
                    revealSafeTiles(
                        safe, hidden, board, state, numMines, clues, neighbors
                    )
                    == "break"
                ):
                    break

            safe.clear()

            if updates:
                continue

            index = make_heuristic(
                updates, board_size, hidden, flagged, clues, neighbors, scoreValue
            )
            # * if/when necesary, will make a guess using calculated scores in make_heuristic()

            break
            # *  break the loop and make the next guess

    end = time.perf_counter()  # * end timer
    timeDelta = end - start  # * calc how much time has passed

    return (
        state["won"],
        timeDelta,
    )  # * return if the game was won (bool) and the amount of time taken


def simulate_bot(
    bot_func: Callable[[int, int, list], tuple],
    side_length,
    num_mines,
    tries,
    neighbors,
):
    """simulate bot_func tries number of times.

    Args:
        bot_func (Callable[[int, int, list], tuple]): the function of the bot you would like to test
        side_length (int): side length of the board
        num_mines (int): number of mines
        tries (int): number of iterations to test the bot over
        neighbors (list): see build_neighbors()

    Returns:
        tuple: (wins: int, avgTime: float)
    """
    wins = 0
    totalTime = 0
    for _ in range(tries):
        isWon, timeDelta = bot_func(side_length, num_mines, neighbors)
        if isWon:
            wins += 1
        totalTime += timeDelta
    return wins, (totalTime / tries)


# * EXAMPLE USE, STORES DATA IN data/dataSmart.csv
TRIES = 10000
SMARTBOT_VERSION = 2
RANDOMBOT_VERSION = 1
TIMESTAMP = None
SIDELENGTH = 10
NUMMINES = 10
NEIGHBORS = build_neighbors(SIDELENGTH)

wins, avgTime = simulate_bot(smartishBot, SIDELENGTH, NUMMINES, TRIES, NEIGHBORS)

data = [
    SIDELENGTH**2,
    TRIES,
    wins,
    NUMMINES,
    (NUMMINES / SIDELENGTH**2) * 100,
    avgTime,
    datetime.now().isoformat(),
    SMARTBOT_VERSION,
]

with open("data/dataSmart.csv", "a+", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(data)
